language: node_js
node_js:
  - "stable"
env:
  global:
  - CODECLIMATE_REPO_TOKEN=ba0c0cc5dd583bdd9c8aaa5f8f3ef0f482b9c316a386ded68ddd8da424c2537a
cache:
  directories:
    - "node_modules"
before_install: cd ./api
install: 
  - npm install
script:
  - npm run test
after_success: 
  - npm run coverage
