language: node_js
node_js:
  - "stable"
env:
  global:
  - CODECLIMATE_REPO_TOKEN=9758487f13d9422ad5d7fd4580163e8d08ade56f8ee474fff7956d2ec0cf3a89
cache:
  directories:
    - "node_modules"
before_install: cd ./api
install: 
  - npm install
script:
  - npm run test
after_success: 
  - npm run coverage
