language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "/api/node_modules"
script:
  - "npm run test"
after_success:
- npm run coveralls
- npm run coveralls
- npm run report-coverage
- ./node_modules/.bin/mocha